Java:
  env_vars:
    - JAVA_HOME
    - JDK_HOME
    - Path: "bin"

Git:
  env_vars:
    - Path: "bin"

Rust:
  env_vars:
    - RUSTUP_HOME: ".rustup"
    - CARGO_HOME: ".cargo"
    - Path: ".cargo\\bin"

Node:
  env_vars:
    - Path: 

Flutter:
  env_vars:
    - Path: "bin"

Android:
  env_vars:
    - ANDROID_HOME
    - Path: "platform-tools"
    - Path: "tools"
    - Path: "tools\\bin"

Maven:
  env_vars:
    - M2_HOME: "..\\.m2"
    - Path: "bin"
